### PR TITLE
Add phpcs to travis

### PR DESCRIPTION
**Pull request by young-steveo**

### CODE REVIEW

**Comment by jrbasso** [comment]
What do you think in use PSR rules on the public projects?

**Comment by young-steveo** [comment]
@jrbasso I don't like the brace rules in PSR-2:

> - Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.
> - Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.

I'm using the Zumba coding standard with slight modifications for this project; I could instead use the PSR-2 rules and modify the brace standard to something more tolerable.  What do you think?

**Comment by jrbasso** [comment]
I would go all or nothing. I like our coding standard, but I am wondering if our open source projects must be compatible with other libraries in the community, following the same standard. I see few places that they consider the project using PSR and seems they give kudos for that.

It is just a thought, we can keep our standards if everyone agrees.

PS: another annoying thing from PSR-2 is the tab/space fight.

**Comment by young-steveo** [comment]
@jrbasso The code is currently compliant with PSR-1 and PSR-4.  These two standards pretty much cover the compatibility issue.

The style standard should only affect contributors, rather than typical users, so I think we can pick and choose what works better for us in this case.

That said, I tried running the sniffer against the source with this ruleset:

``` xml
<?xml version="1.0"?>
<ruleset name="Swivel">
    <description>Zumba Swivel Coding Standard</description>
    <arg value="np"/>

    <rule ref="PSR2">
        <exclude name="PSR2.Classes.ClassDeclaration.OpenBraceNewLine"/>
        <exclude name="Squiz.Functions.MultiLineFunctionDeclaration.BraceOnSameLine"/>
    </rule>
    <rule ref="Generic.Functions.OpeningFunctionBraceKernighanRitchie"/>
</ruleset>
```

Which basically just uses PSR-2 except without the braces needing to be on their own lines.  There were only 5 errors and 1 warning.  The advantages to the above ruleset:
- It doesn't deviate too much from the way we define the Zumba standard, and
- It's still very close to PSR-2 for those contributors who prefer PSR-2.

@cjsaylor What do you think?

**Comment by jrbasso** [comment]
@young-steveo I like that, probably we can include this ruleset on [zumba/zumba-coding-standards](https://github.com/zumba/zumba-coding-standards) repo. So we can add/remove things based on this ruleset.

For example, [cakephp has few more rules](https://github.com/cakephp/cakephp-codesniffer/blob/master/CakePHP/ruleset.xml) that can be applied, even when not required by PSR-2. We can copy some of those since they are the same of Zumba's coding standard.

**Comment by cjsaylor** [comment]
@young-steveo How different is it from our current standards in the zumba coding standards repo? If it isn't much different, then it may be easier to just require as a dev dependency and leave it at that.

Whichever way we decide to go with on standards, as long as they are defined and easy for contributors to run, I'm fine with running the above or the full zumba coding standards. I guess with the above, there isn't a necessity to do a dev dependency (and also do an overwrite for this project).

**Comment by jrbasso** [comment]
Ok, merging for now. Once we have the coding standards in place we open a new PR for all our open source projects.

**Comment by young-steveo** [comment]
@jrbasso :+1: Sounds like a plan.

**Pull request merged**
